### ISSUE TITLE
Document how to associate new file extension?

### ISSUE THREAD

**Issue by FGasper** [samosad/vscode-template-toolkit#1]
Hello,

I’m on a project that uses `.tmpl` as an extension for TT2 files. Is there a way to have your plugin recognize this extension?

Thank you!

**Comment by samosad** [comment]
You just need to click on file type at the bottom right corner of VSCode window, and then select "Configure file association for ..." than you can select TT as language for `.tmpl` files

![image](https://user-images.githubusercontent.com/1986478/44299823-73eee480-a305-11e8-9115-240807a44bea.png)
