### ISSUE TITLE
Not published to Visual Studio Marketplace

### ISSUE THREAD

**Issue by kimulaco** [samosad/vscode-template-toolkit#4]
This extension has update v0.0.5 with the #3, but has not been updated from v0.0.4 in Visual Studio Marketplace.
https://marketplace.visualstudio.com/items?itemName=samosad.tt

I also want to update the Visual Studio Marketplace.

**Comment by samosad** [comment]
updated!

**Comment by kimulaco** [comment]
Thank you!
I confirmed the update!
