### ISSUE TITLE
VSCodium installation instructions

### ISSUE THREAD

**Issue by ernstki** [samosad/vscode-template-toolkit#6]
Hi, and thanks for making this extension!

I'm new to VS Code and VS Codium, so I am not really hip to all the differences between the two, except the obvious differences of no telemetry and you can't use proprietary extensions like Remote with Codium.

I assume there's also a different "marketplace" for the two of them. Searching for "template toolkit" doesn't turn up any results in Codium's marketplace. However, I noticed an _Install from VSIX…_ menu option, and took a chance that it would work on a .zip of the GitHub repository with the extension changed to `.vsix`.

![Screenshot showing the 'Install from VSIX…' menu option in VSCodium](https://user-images.githubusercontent.com/4009681/211998073-ff7d0a56-90fb-40c7-8046-02f0d3834d81.png)

That _nearly_ works. You need to rename the top-level directory within the .zip to be `extension`. The archive tool in my Linux distribution (elementary OS, Ubuntu 22.04) allows one to easily rename directories within a compressed archive; your mileage may vary. On macOS, you'll probably just have to extract, rename the extracted folder, then create a new .zip file.

Finally, change the `.zip` extension to `.vsix`. Then choose this file from the file open dialog box that appears when you choose "Install from VSIX…" from the menu in the Extensions sidebar.

If you think it's worthwhile, I can do a PR to add these instructions to the README, but I figure just having it documented as a (closed) GitHub issue is probably sufficient for the handful of people who need this.

**Comment by samosad** [comment]
Hi! Sorry, don't have time for this. If you need it pls make a PR, I will review and merge

**Comment by ernstki** [comment]
No worries. It seems fine to just close this ticket. I imagine the Venn diagram overlap between the people who use VSCodium and the people who would check a project's issue tracker for installation help if the README doesn't cover it is a large overlap. `;)`
